<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IncludeBuildOutput>false</IncludeBuildOutput>

        <RootNamespace>Hertzole.SourceGenUtils</RootNamespace>
        <PackageId>Hertzole.SourceGenUtils</PackageId>
        <AssemblyName>SourceGenUtils</AssemblyName>

        <Authors>Hertzole</Authors>
        <Company>Hertzole</Company>
        <Title>SourceGenUtils</Title>
        <PackageProjectUrl>https://github.com/Hertzole/sourcegen-utils</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Hertzole/sourcegen-utils</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Description>Provides common utilities for source generation.
            Use code writer for building your code and common extensions to speed up development and get consistent results.
        </Description>
        <PackageTags>sourcegen, source, generator, sourcegenerator, incremental, incrementalgenerator, util, utility, utils, string, stringbuilder, builder, code, writer, codewriter</PackageTags>
        <NeutralLanguage>en-US</NeutralLanguage>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <NoWarn>NU5128</NoWarn> <!-- Ignore warning about no files in libs folder. Generator publishes to analyzer folder. -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <!-- Package the generator in the analyzer directory of the nuget package -->
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    </ItemGroup>

</Project>


