using System;
using System.Text;
using System.Threading;
using Hertzole.SourceGen;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenUtils.Sample;

[Generator]
public class SampleGenerator : IIncrementalGenerator
{
    private const string ATTRIBUTE_SOURCE = @" // <auto-generated/>
[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
internal sealed class SampleGeneratorAttribute : global::System.Attribute { }
";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("SampleGeneratorAttribute.g.cs", SourceText.From(ATTRIBUTE_SOURCE, Encoding.UTF8));
        });

        IncrementalValuesProvider<INamedTypeSymbol> provider = context.SyntaxProvider
                                                                      .ForAttributeWithMetadataName("SampleGeneratorAttribute", Predicate, Transform)
                                                                      .Where(x => x is not null)!;

        context.RegisterSourceOutput(provider, Execute);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken arg2)
    {
        return true;
    }

    private static INamedTypeSymbol? Transform(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        return context.TargetSymbol as INamedTypeSymbol;
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol symbol)
    {
        Log.Info("Execute");

        try
        {
            using CodeWriter writer = new CodeWriter();

            writer.Append(symbol);

            if (!symbol.IsStatic)
            {
                writer.AppendLine(" : global::System.IDisposable");
                using (writer.WithBlock())
                {
                    writer.AppendLine("public void Dispose()");
                    using (writer.WithBlock())
                    {
                        writer.AppendLine("// Dispose me uwu");
                    }
                }
            }
            else
            {
                writer.AppendLine();
                using (writer.WithBlock())
                {
                    writer.AppendLine("public static void DoThing()");
                    using (writer.WithBlock())
                    {
                        writer.AppendLine("// Does the thing you've always wanted...");
                    }
                }
            }

            context.AddSource(symbol.Name, writer);

            Log.Info("Added source");
        }

        catch (Exception e)
        {
            Log.Error(e);
        }
    }
}