using System.Linq;
using Hertzole.SourceGenUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace SourceGenUtils.Tests;

public class GeneratorTests
{
    private const string SourceWithStaticCalls = @"
using Hertzole.SourceGen;

public class MyClass
{
    public void DoSomething()
    {
        CodeWriter.StaticTest();
        CodeWriter.Test();
    }
}";

    private const string SourceWithInstanceCalls = @"
using Hertzole.SourceGen;

public class MyClass
{
    public void DoSomething()
    {
        CodeWriter writer = new CodeWriter();
        writer.Test();
    }
}";

    private const string ExpectedAllCalled = @"// <auto-generated/>

namespace Hertzole.SourceGen
{
    internal sealed partial class CodeWriter
    {
        public void Test()
        {
            // TODO: Implement this bad boy
        }

        public static void StaticTest()
        {
            // TODO: Implement this bad boy
        }
    }
}
";

    private const string ExpectedInstanceOnly = @"// <auto-generated/>

namespace Hertzole.SourceGen
{
    internal sealed partial class CodeWriter
    {
        public void Test()
        {
            // TODO: Implement this bad boy
        }

        public static void StaticTest()
        {
        }
    }
}
";

    private const string ExpectedNoCalls = @"// <auto-generated/>

namespace Hertzole.SourceGen
{
    internal sealed partial class CodeWriter
    {
        public void Test()
        {
        }

        public static void StaticTest()
        {
        }
    }
}
";

    [Fact]
    public void StaticAndInstanceCalls_GetTodo()
    {
        var generator = new Generator();
        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create("Test",
            new[] { CSharpSyntaxTree.ParseText(SourceWithStaticCalls) },
            new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var codeWriterFile = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("CodeWriter.g.cs")
                && !t.FilePath.EndsWith("Shell.g.cs"));
        Assert.Equal(ExpectedAllCalled, codeWriterFile.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void InstanceMethodCall_DetectedViaSemanticModel()
    {
        var generator = new Generator();
        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create("Test",
            new[] { CSharpSyntaxTree.ParseText(SourceWithInstanceCalls) },
            new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var codeWriterFile = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("CodeWriter.g.cs")
                && !t.FilePath.EndsWith("Shell.g.cs"));
        Assert.Equal(ExpectedInstanceOnly, codeWriterFile.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void EmptyBodiesWhenNoCalls()
    {
        var generator = new Generator();
        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create("Test",
            new[] { CSharpSyntaxTree.ParseText(@"
public class MyClass
{
}") },
            new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var codeWriterFile = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("CodeWriter.g.cs")
                && !t.FilePath.EndsWith("Shell.g.cs"));
        Assert.Equal(ExpectedNoCalls, codeWriterFile.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
}
